export const GET_NOTICES = 'GET_NOTICES'
export const DELETE_NOTICE = 'DELETE_NOTICE'
export const HANDLE_NOTICE_MODAL = 'HANDLE_NOTICE_MODAL'
export const HANDLE_NOTICE_FORM_CHANGE = 'HANDLE_NOTICE_FORM_CHANGE'