//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeBoardAPI.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NoticeId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime PostedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public int IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
